source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'FontAwesome.swift'
pod 'Font-Awesome-Swift', '~> 1.0.0'

platform :ios, '8.0'
pod 'PayPal-iOS-SDK'

pod 'Parse', '~> 1.7.1'
pod 'ParseUI', '~> 1.1.3'
pod 'YRADScrollView', '~> 1.0.0'


pod 'Facebook-iOS-SDK'
pod 'BranchInvite'